FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma.config.ts ./
COPY prisma ./prisma
ENV DATABASE_URL="postgresql://qrsystem:qrsystem_dev_password@localhost:5432/qrsystem"
RUN npx prisma generate

COPY lib ./lib
COPY shared ./shared
COPY services/payment-service ./services/payment-service

WORKDIR /app/services/payment-service

EXPOSE 3005

CMD ["node", "app.js"]

